# Terraform Provider testing workflow.
name: Validation and Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths-ignore:
      - "README.md"
      - ".idea"
      - ".vscode"
      - public

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  build_test:
    name: Build, Validation, and Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800
        with:
          terraform_wrapper: false
      - run: go generate ./...
      - name: Generated docs git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
      - name: Run linters
        uses: golangci/golangci-lint-action@v8.0.0 # v6.5.0
      - run: go mod download
      - name: Build Check
        run: go build -v .
      - name: Unit Tests
        run: task test



  # Run acceptance tests in a matrix with Terraform CLI versions
  acc_test:
    name: Terraform Provider Acceptance Tests
    needs: build_test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - "1.7.*"
          - "1.8.*"
          - "1.9.*"
          - "1.10.*"
          - "1.11.*"
          - "1.12.*"
    steps:
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800 # v3.1.0
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - run: go install gotest.tools/gotestsum@latest
      - run: go install github.com/bitfield/gotestdox/cmd/gotestdox@latest
      - env:
          ZENDESK_SUBDOMAIN: ${{ vars.ZENDESK_SUBDOMAIN }}
          ZENDESK_USERNAME: ${{ secrets.ZENDESK_USERNAME }}
          ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
        run: task test ACC_ONLY=true
